name: firebase_messaging_helper
description: This plugin combine firebase_messaging with awesome_notification to help you esier to implement firebase notification.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  
  flutter:
    sdk: flutter
  
  box_widgets:
    git: https://github.com/vursin/box_widgets

  hive_flutter: ^1.1.0
  awesome_notifications: ^0.6.21
  firebase_messaging: ^12.0.1
  firebase_core: ^1.20.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: